### PR TITLE
LargeLexer and Windows support.

### PR DESCRIPTION
**Pull request by graknol**
Ref.: https://github.com/antlr/antlr4/pull/2728#issuecomment-619933934
To complete the tests, you need to use the beta-channel of dart2native.
Also, I ran them with JDK 8.

### CODE REVIEW

**Comment by graknol** [comment]
@lingyv-li 
Hi, would you be so kind to review and merge the changes, so that we could get #2728 merged? 😊

**Comment by lingyv-li** [comment]
Thank you for the pull request! I didn't check github for some time and didn't have email notification setup 😢.
Looks great! Will you also add yourself to the contributors list?

**Comment by graknol** [comment]
> Thank you for the pull request! I didn't check github for some time and didn't have email notification setup 😢.
> Looks great! Will you also add yourself to the contributors list?

Added myself to it 😊

**Comment by lingyv-li** [comment]
Thank you!

**Pull request merged**
